# Generated by Django 4.2.5 on 2023-10-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='srv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.CharField(max_length=50)),
                ('tel_act', models.CharField(max_length=50)),
                ('fc_activacion', models.DateField()),
                ('fc_estado', models.DateField()),
                ('last_update', models.DateField()),
                ('puntos', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'srv',
            },
        ),
    ]
